package com.marasm.dmg.generators.swift;

import com.marasm.dmg.*;
import com.marasm.dmg.generators.java.CouchDBGenerator;

import java.io.IOException;
import java.io.OutputStream;
import java.util.ArrayList;
import java.util.Collection;

/**
 * Created by vhq473 on 01.09.2016.
 */
public class SwiftGenerator implements Generator
{
    private String file_header = "///////////////////////////////////////////\n"+
                                 "//                                       //\n"+
                                 "// Code generated by DMG Swift Generator //\n"+
                                 "// https://github.com/marasm-group/dmg   //\n"+
                                 "//                                       //\n"+
                                 "///////////////////////////////////////////\n"+
                                 "import Foundation\n";
    String result = "";


    public String tmp_arr = "TMP_ARRAY";
    public String tmp_obj = "TMP_OBJ";
    public String tmp_json_obj = "TMP_JSON_OBJ";


    boolean to_json = false;
    boolean from_json = false;
    private boolean couchdb = false;
    private String str;

    void append(String str)
    {
        result += str+"\n";
    }
    public void generate(DMGObject object)
    {
        String classStr = "public class "+capitalizeFirst(object.name);
        if(to_json)
        {
            classStr += " : CustomStringConvertible, CustomDebugStringConvertible";
        }
        append(classStr);
        append("{");
        for (Field f: object.fields)
        {
            append("public var "+f.name+": "+type(f,f.isArray)+"?");
        }
        append("public init(){}");
        if(from_json)
        {
            append("//MARK: JSON deserialization");
            String tmp1 = "{\n"+
                          "guard let data = jsonString.dataUsingEncoding(NSUTF8StringEncoding) else {return nil}\n"+
                          "do{\n"+
                          "if let json = try NSJSONSerialization.JSONObjectWithData(data, options: NSJSONReadingOptions()) as? [String: AnyObject]\n{";
            String tmp2 = "else {return nil}\n"+
                          "} catch {\n"+
                          "print(error)\n"+
                          "return nil\n"+
                          "}\n}";
            append("public convenience init?(jsonString: String)");
            append(tmp1);
            append("self.init(jsonDictionary: json)\n}");
            append(tmp2);
            append("public convenience init(jsonDictionary json: [String: AnyObject])\n{");
            append("self.init()");
            for (Field f : object.fields)
            {
                if(f.object != null && f.isArray)
                {
                    append("if let "+tmp_arr+" = json[\""+f.name+"\"] as? [AnyObject]\n" +
                           "{\n" +
                           "self."+f.name+" = ["+capitalizeFirst(f.name)+"]()\n" +
                           "for "+tmp_json_obj+" in "+tmp_arr+"\n" +
                           "{\n" +
                           "if let "+tmp_json_obj+" = "+tmp_json_obj+" as?[String : AnyObject]\n" +
                           "{\n" +
                           "self."+f.name+"?.append("+capitalizeFirst(f.name)+"(jsonDictionary: "+tmp_json_obj+"))\n" +
                           "}\n" +
                           "}\n" +
                           "} else {\n" +
                           "self."+f.name+" = nil\n" +
                           "}");
                }
                else
                {
                    append("if let " + tmp_obj + " = json[\"" + f.name + "\"] as?" + type(f, f.isArray) + "{");
                    append("self." + f.name + " = " + tmp_obj + "");
                    append("} else {");
                    append("self." + f.name + " = nil");
                    append("}");
                }
            }
            append("}");
        }
        if(to_json)
        {
            append("//MARK: JSON serialization");
            append("public var jsonDictionary : [String:AnyObject]\n"+
                   "{\n");
            append("var "+tmp_json_obj+" = [String:AnyObject]()");
            for (Field f : object.fields)
            {
                if (f.object != null)
                {
                    if(f.isArray)
                    {
                        append("var "+tmp_arr+" = [AnyObject]()\n" +
                                "        for "+tmp_obj+" in self."+f.name+" ?? [] {\n" +
                                "            "+tmp_arr+".append("+tmp_obj+".jsonDictionary)\n" +
                                "        }\n" +
                                "        TMP_JSON_OBJ[\""+f.name+"\"] = "+tmp_arr);
                    }
                    else
                    {
                        append("if let "+tmp_obj+" = self."+f.name+"?.jsonDictionary{");
                        append(tmp_json_obj+"[\""+f.name+"\"] = "+tmp_obj+"");
                        append("}");
                    }
                }
                else
                {
                    append("if let "+tmp_obj+" = self."+f.name+"{");
                    append(tmp_json_obj+"[\""+f.name+"\"] = "+tmp_obj+"");
                    append("}");
                }
            }
            append("return "+tmp_json_obj);
            append("}");
            append("public var jsonPrettyString : String?\n"+
                    "{\n"+
                    "do{\n"+
                    "let data = try NSJSONSerialization.dataWithJSONObject(jsonDictionary, options: .PrettyPrinted)\n"+
                    "return String(data: data,encoding: NSUTF8StringEncoding)\n"+
                    "} catch let e {print(e)}\n"+
                    "return nil\n"+
                    "}\n"+
                    "public var jsonString : String?\n"+
                    "{\n"+
                    "do{\n"+
                    "let data = try NSJSONSerialization.dataWithJSONObject(jsonDictionary, options: NSJSONWritingOptions(rawValue: 0))\n"+
                    "return String(data: data,encoding: NSUTF8StringEncoding)\n"+
                    "} catch let e {print(e)}\n"+
                    "return nil\n"+
                    "}");
            append("//MARK: CustomStringConvertible, CustomDebugStringConvertible");
            append("public var debugDescription : String {return self.jsonPrettyString ?? \"<ERROR>\"}");
            append("public var description : String {return self.jsonString ?? \"<ERROR>\"}");
        }

        append("\n}//"+object.name);
        for (Field f: object.fields)
        {
            if (f.type ==  Type.Object)
            {
                generate(f.object);
            }
        }
    }
    public void generate(ArrayList<DMGObject> objects)
    {
        for (DMGObject obj : objects)
        {
            generate(obj);
        }
    }

    public String type(Field f)
    {
        return type(f,false);
    }
    public String type(Field f, boolean array)
    {
        String res = "";
        switch (f.type)
        {
            case Object:
                res = capitalizeFirst(f.object.name);
                break;
            case String:
                res = "String";
                break;
            case Int:
                res = "Int";
                break;
            case Real:
                res = "Double";
                break;
            case Number:
                res = "NSNumber";
                break;
            case Bool:
                res = "Bool";
                break;
            default:
                res = "ERROR_TYPE";
                break;
        }
        if(array)
        {
            res = "["+ res + "]";
        }
        return res;
    }

    public String capitalizeFirst(String str)
    {
        return str.substring(0, 1).toUpperCase() + str.substring(1);
    }

    public void enableFeatures(Collection<Feature> features)
    {
        for (Feature f : features)
        {
            switch (f)
            {
                case from_json:
                    this.from_json = true;
                    break;
                case to_json:
                    this.to_json = true;
                    break;
                /*case couchdb:
                    this.couchdb = true;
                    break;*/
                default:
                    Log.e(this,"Feature "+f+" is unsupported!");
                    System.exit(-1);
            }
        }
    }
    public void disableFeatures(Collection<Feature> features)
    {
        for (Feature f : features)
        {
            switch (f)
            {
                case from_json:
                    this.from_json = false;
                    break;
                case to_json:
                    this.to_json = false;
                    break;
                /*case couchdb:
                    this.couchdb = false;
                    break;*/
                default:
                    Log.e(this,"Feature "+f+" is unsupported!");
                    break;
            }
        }
    }

    public void beginGeneration()
    {
        file_header+="// DMG version: "+Utils.getVersion()+"\n";
        append(file_header);
    }

    public void endGeneration(OutputStream stream) throws IOException
    {
        stream.write(result.getBytes());
    }
}
